//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference1 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.calc/")]
    public partial class ClassNotFoundException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private stackTraceElement[] exceptionField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stackTrace", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public stackTraceElement[] exception {
            get {
                return this.exceptionField;
            }
            set {
                this.exceptionField = value;
                this.RaisePropertyChanged("exception");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.calc/")]
    public partial class stackTraceElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.calc/")]
    public partial class IOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.calc/")]
    public partial class JSONException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.calc/", ConfigurationName="ServiceReference1.Calculate")]
    public interface Calculate {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.calc/Calculate/helloRequest", ReplyAction="http://ws.calc/Calculate/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebApplication1.ServiceReference1.helloResponse hello(WebApplication1.ServiceReference1.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.calc/Calculate/helloRequest", ReplyAction="http://ws.calc/Calculate/helloResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.helloResponse> helloAsync(WebApplication1.ServiceReference1.helloRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.calc/Calculate/ReadFileRequest", ReplyAction="http://ws.calc/Calculate/ReadFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebApplication1.ServiceReference1.ReadFileResponse ReadFile(WebApplication1.ServiceReference1.ReadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.calc/Calculate/ReadFileRequest", ReplyAction="http://ws.calc/Calculate/ReadFileResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.ReadFileResponse> ReadFileAsync(WebApplication1.ServiceReference1.ReadFileRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.calc/Calculate/CalculateClassRequest", ReplyAction="http://ws.calc/Calculate/CalculateClassResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebApplication1.ServiceReference1.ClassNotFoundException), Action="http://ws.calc/Calculate/CalculateClass/Fault/ClassNotFoundException", Name="ClassNotFoundException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebApplication1.ServiceReference1.IOException), Action="http://ws.calc/Calculate/CalculateClass/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebApplication1.ServiceReference1.JSONException), Action="http://ws.calc/Calculate/CalculateClass/Fault/JSONException", Name="JSONException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebApplication1.ServiceReference1.CalculateClassResponse CalculateClass(WebApplication1.ServiceReference1.CalculateClassRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.calc/Calculate/CalculateClassRequest", ReplyAction="http://ws.calc/Calculate/CalculateClassResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.CalculateClassResponse> CalculateClassAsync(WebApplication1.ServiceReference1.CalculateClassRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.calc/Calculate/workWithJarRequest", ReplyAction="http://ws.calc/Calculate/workWithJarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebApplication1.ServiceReference1.workWithJarResponse workWithJar(WebApplication1.ServiceReference1.workWithJarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.calc/Calculate/workWithJarRequest", ReplyAction="http://ws.calc/Calculate/workWithJarResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.workWithJarResponse> workWithJarAsync(WebApplication1.ServiceReference1.workWithJarRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.calc/Calculate/additionRequest", ReplyAction="http://ws.calc/Calculate/additionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebApplication1.ServiceReference1.additionResponse addition(WebApplication1.ServiceReference1.additionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.calc/Calculate/additionRequest", ReplyAction="http://ws.calc/Calculate/additionResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.additionResponse> additionAsync(WebApplication1.ServiceReference1.additionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://ws.calc/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.calc/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://ws.calc/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.calc/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadFile", WrapperNamespace="http://ws.calc/", IsWrapped=true)]
    public partial class ReadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.calc/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fileName;
        
        public ReadFileRequest() {
        }
        
        public ReadFileRequest(string fileName) {
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadFileResponse", WrapperNamespace="http://ws.calc/", IsWrapped=true)]
    public partial class ReadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.calc/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public ReadFileResponse() {
        }
        
        public ReadFileResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalculateClass", WrapperNamespace="http://ws.calc/", IsWrapped=true)]
    public partial class CalculateClassRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.calc/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.calc/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] fileArray;
        
        public CalculateClassRequest() {
        }
        
        public CalculateClassRequest(string fileName, byte[] fileArray) {
            this.fileName = fileName;
            this.fileArray = fileArray;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalculateClassResponse", WrapperNamespace="http://ws.calc/", IsWrapped=true)]
    public partial class CalculateClassResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.calc/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public CalculateClassResponse() {
        }
        
        public CalculateClassResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="workWithJar", WrapperNamespace="http://ws.calc/", IsWrapped=true)]
    public partial class workWithJarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.calc/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public workWithJarRequest() {
        }
        
        public workWithJarRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="workWithJarResponse", WrapperNamespace="http://ws.calc/", IsWrapped=true)]
    public partial class workWithJarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.calc/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public workWithJarResponse() {
        }
        
        public workWithJarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addition", WrapperNamespace="http://ws.calc/", IsWrapped=true)]
    public partial class additionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.calc/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double x;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.calc/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double y;
        
        public additionRequest() {
        }
        
        public additionRequest(double x, double y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="additionResponse", WrapperNamespace="http://ws.calc/", IsWrapped=true)]
    public partial class additionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.calc/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public additionResponse() {
        }
        
        public additionResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculateChannel : WebApplication1.ServiceReference1.Calculate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculateClient : System.ServiceModel.ClientBase<WebApplication1.ServiceReference1.Calculate>, WebApplication1.ServiceReference1.Calculate {
        
        public CalculateClient() {
        }
        
        public CalculateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.helloResponse WebApplication1.ServiceReference1.Calculate.hello(WebApplication1.ServiceReference1.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            WebApplication1.ServiceReference1.helloRequest inValue = new WebApplication1.ServiceReference1.helloRequest();
            inValue.name = name;
            WebApplication1.ServiceReference1.helloResponse retVal = ((WebApplication1.ServiceReference1.Calculate)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.helloResponse> WebApplication1.ServiceReference1.Calculate.helloAsync(WebApplication1.ServiceReference1.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.helloResponse> helloAsync(string name) {
            WebApplication1.ServiceReference1.helloRequest inValue = new WebApplication1.ServiceReference1.helloRequest();
            inValue.name = name;
            return ((WebApplication1.ServiceReference1.Calculate)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.ReadFileResponse WebApplication1.ServiceReference1.Calculate.ReadFile(WebApplication1.ServiceReference1.ReadFileRequest request) {
            return base.Channel.ReadFile(request);
        }
        
        public string ReadFile(string fileName) {
            WebApplication1.ServiceReference1.ReadFileRequest inValue = new WebApplication1.ServiceReference1.ReadFileRequest();
            inValue.fileName = fileName;
            WebApplication1.ServiceReference1.ReadFileResponse retVal = ((WebApplication1.ServiceReference1.Calculate)(this)).ReadFile(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.ReadFileResponse> WebApplication1.ServiceReference1.Calculate.ReadFileAsync(WebApplication1.ServiceReference1.ReadFileRequest request) {
            return base.Channel.ReadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.ReadFileResponse> ReadFileAsync(string fileName) {
            WebApplication1.ServiceReference1.ReadFileRequest inValue = new WebApplication1.ServiceReference1.ReadFileRequest();
            inValue.fileName = fileName;
            return ((WebApplication1.ServiceReference1.Calculate)(this)).ReadFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.CalculateClassResponse WebApplication1.ServiceReference1.Calculate.CalculateClass(WebApplication1.ServiceReference1.CalculateClassRequest request) {
            return base.Channel.CalculateClass(request);
        }
        
        public string CalculateClass(string fileName, byte[] fileArray) {
            WebApplication1.ServiceReference1.CalculateClassRequest inValue = new WebApplication1.ServiceReference1.CalculateClassRequest();
            inValue.fileName = fileName;
            inValue.fileArray = fileArray;
            WebApplication1.ServiceReference1.CalculateClassResponse retVal = ((WebApplication1.ServiceReference1.Calculate)(this)).CalculateClass(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.CalculateClassResponse> WebApplication1.ServiceReference1.Calculate.CalculateClassAsync(WebApplication1.ServiceReference1.CalculateClassRequest request) {
            return base.Channel.CalculateClassAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.CalculateClassResponse> CalculateClassAsync(string fileName, byte[] fileArray) {
            WebApplication1.ServiceReference1.CalculateClassRequest inValue = new WebApplication1.ServiceReference1.CalculateClassRequest();
            inValue.fileName = fileName;
            inValue.fileArray = fileArray;
            return ((WebApplication1.ServiceReference1.Calculate)(this)).CalculateClassAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.workWithJarResponse WebApplication1.ServiceReference1.Calculate.workWithJar(WebApplication1.ServiceReference1.workWithJarRequest request) {
            return base.Channel.workWithJar(request);
        }
        
        public int workWithJar(string arg0) {
            WebApplication1.ServiceReference1.workWithJarRequest inValue = new WebApplication1.ServiceReference1.workWithJarRequest();
            inValue.arg0 = arg0;
            WebApplication1.ServiceReference1.workWithJarResponse retVal = ((WebApplication1.ServiceReference1.Calculate)(this)).workWithJar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.workWithJarResponse> WebApplication1.ServiceReference1.Calculate.workWithJarAsync(WebApplication1.ServiceReference1.workWithJarRequest request) {
            return base.Channel.workWithJarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.workWithJarResponse> workWithJarAsync(string arg0) {
            WebApplication1.ServiceReference1.workWithJarRequest inValue = new WebApplication1.ServiceReference1.workWithJarRequest();
            inValue.arg0 = arg0;
            return ((WebApplication1.ServiceReference1.Calculate)(this)).workWithJarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.additionResponse WebApplication1.ServiceReference1.Calculate.addition(WebApplication1.ServiceReference1.additionRequest request) {
            return base.Channel.addition(request);
        }
        
        public double addition(double x, double y) {
            WebApplication1.ServiceReference1.additionRequest inValue = new WebApplication1.ServiceReference1.additionRequest();
            inValue.x = x;
            inValue.y = y;
            WebApplication1.ServiceReference1.additionResponse retVal = ((WebApplication1.ServiceReference1.Calculate)(this)).addition(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.additionResponse> WebApplication1.ServiceReference1.Calculate.additionAsync(WebApplication1.ServiceReference1.additionRequest request) {
            return base.Channel.additionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.additionResponse> additionAsync(double x, double y) {
            WebApplication1.ServiceReference1.additionRequest inValue = new WebApplication1.ServiceReference1.additionRequest();
            inValue.x = x;
            inValue.y = y;
            return ((WebApplication1.ServiceReference1.Calculate)(this)).additionAsync(inValue);
        }
    }
}
